### ISSUE TITLE
[BUG] Missing typescript types 

### ISSUE THREAD

**Issue by aldulea** [Adyen/adyen-node-api-library#219]
**Describe the bug**
using version 2.2.0, I cannot start a typescript project including the library.

Using the previous version 2.1.8 everything works fine.

**To Reproduce**
```npm install --save @adyen/api-library@2.2.0```

**Expected behavior**
project runs

**Screenshots**
Not screenshots but logs of the errors:
```
node_modules/@adyen/api-library/dist/lib/src/client.d.ts:11:18 - error TS2304: Cannot find name 'Environment'.

11     environment: Environment;
                    ~~~~~~~~~~~

node_modules/@adyen/api-library/dist/lib/src/client.d.ts:16:18 - error TS2304: Cannot find name 'Environment'.

16     environment: Environment;
                    ~~~~~~~~~~~

node_modules/@adyen/api-library/dist/lib/src/client.d.ts:22:18 - error TS2304: Cannot find name 'Environment'.

22     environment: Environment;
                    ~~~~~~~~~~~

node_modules/@adyen/api-library/dist/lib/src/client.d.ts:28:18 - error TS2304: Cannot find name 'Environment'.

28     environment: Environment;
                    ~~~~~~~~~~~

node_modules/@adyen/api-library/dist/lib/src/client.d.ts:34:18 - error TS2304: Cannot find name 'Environment'.

34     environment: Environment;
                    ~~~~~~~~~~~

node_modules/@adyen/api-library/dist/lib/src/client.d.ts:37:18 - error TS2304: Cannot find name 'Environment'.

37     environment: Environment;
                    ~~~~~~~~~~~

node_modules/@adyen/api-library/dist/lib/src/client.d.ts:41:18 - error TS2304: Cannot find name 'Environment'.

41     environment: Environment;
                    ~~~~~~~~~~~

node_modules/@adyen/api-library/dist/lib/src/client.d.ts:72:33 - error TS2304: Cannot find name 'Environment'.

72     setEnvironment(environment: Environment, liveEndpointUrlPrefix?: string): void;
                                   ~~~~~~~~~~~

node_modules/@adyen/api-library/dist/lib/src/config.d.ts:5:19 - error TS2304: Cannot find name 'Environment'.

5     environment?: Environment;
                    ~~~~~~~~~~~

node_modules/@adyen/api-library/dist/lib/src/config.d.ts:24:19 - error TS2304: Cannot find name 'Environment'.

24     environment?: Environment;
                     ~~~~~~~~~~~

node_modules/@adyen/api-library/dist/lib/src/httpClient/clientInterface.d.ts:7:105 - error TS2503: Cannot find namespace 'IRequest'.

7     request(endpoint: string, json: string, config: Config, isApiKeyRequired: boolean, requestOptions?: IRequest.Options): Promise<string | HttpClientException | ApiException>;
                                                                                                          ~~~~~~~~

node_modules/@adyen/api-library/dist/lib/src/httpClient/httpURLConnectionClient.d.ts:11:101 - error TS2503: Cannot find namespace 'IRequest'.

11     request(endpoint: string, json: string, config: Config, isApiRequired: boolean, requestOptions: IRequest.Options): Promise<string | HttpClientException | ApiException>;
                                                                                                       ~~~~~~~~

node_modules/@adyen/api-library/dist/lib/src/services/binLookup.d.ts:7:33 - error TS2503: Cannot find namespace 'IBinLookup'.

7     get3dsAvailability(request: IBinLookup.ThreeDSAvailabilityRequest): Promise<IBinLookup.ThreeDSAvailabilityResponse>;
                                  ~~~~~~~~~~

node_modules/@adyen/api-library/dist/lib/src/services/binLookup.d.ts:7:81 - error TS2503: Cannot find namespace 'IBinLookup'.

7     get3dsAvailability(request: IBinLookup.ThreeDSAvailabilityRequest): Promise<IBinLookup.ThreeDSAvailabilityResponse>;
                                                                                  ~~~~~~~~~~

node_modules/@adyen/api-library/dist/lib/src/services/binLookup.d.ts:8:30 - error TS2503: Cannot find namespace 'IBinLookup'.

8     getCostEstimate(request: IBinLookup.CostEstimateRequest): Promise<IBinLookup.CostEstimateResponse>;
                               ~~~~~~~~~~

node_modules/@adyen/api-library/dist/lib/src/services/binLookup.d.ts:8:71 - error TS2503: Cannot find namespace 'IBinLookup'.

8     getCostEstimate(request: IBinLookup.CostEstimateRequest): Promise<IBinLookup.CostEstimateResponse>;
                                                                        ~~~~~~~~~~

node_modules/@adyen/api-library/dist/lib/src/services/checkout.d.ts:11:74 - error TS2503: Cannot find namespace 'IRequest'.

11     payments(paymentsRequest: ICheckout.PaymentRequest, requestOptions?: IRequest.Options): Promise<ICheckout.PaymentResponse>;
                                                                            ~~~~~~~~

node_modules/@adyen/api-library/dist/lib/src/services/checkout.d.ts:15:91 - error TS2503: Cannot find namespace 'IRequest'.

15     paymentSession(paymentSessionRequest: ICheckout.PaymentSetupRequest, requestOptions?: IRequest.Options): Promise<ICheckout.PaymentSetupResponse>;
                                                                                             ~~~~~~~~

node_modules/@adyen/api-library/dist/lib/src/services/checkoutUtility.d.ts:6:35 - error TS2503: Cannot find namespace 'ICheckoutUtility'.

6     originKeys(originKeysRequest: ICheckoutUtility.CheckoutUtilityRequest): Promise<ICheckoutUtility.CheckoutUtilityResponse>;
                                    ~~~~~~~~~~~~~~~~

node_modules/@adyen/api-library/dist/lib/src/services/checkoutUtility.d.ts:6:85 - error TS2503: Cannot find namespace 'ICheckoutUtility'.

6     originKeys(originKeysRequest: ICheckoutUtility.CheckoutUtilityRequest): Promise<ICheckoutUtility.CheckoutUtilityResponse>;
                                                                                      ~~~~~~~~~~~~~~~~

node_modules/@adyen/api-library/dist/lib/src/services/modification.d.ts:16:44 - error TS2503: Cannot find namespace 'IPayments'.

16     capture(captureRequest: GenericRequest<IPayments.ModificationRequest>, requestOptions?: IRequest.Options): Promise<IPayments.ModificationResult>;
                                              ~~~~~~~~~

node_modules/@adyen/api-library/dist/lib/src/services/modification.d.ts:16:93 - error TS2503: Cannot find namespace 'IRequest'.

16     capture(captureRequest: GenericRequest<IPayments.ModificationRequest>, requestOptions?: IRequest.Options): Promise<IPayments.ModificationResult>;
                                                                                               ~~~~~~~~

node_modules/@adyen/api-library/dist/lib/src/services/modification.d.ts:16:120 - error TS2503: Cannot find namespace 'IPayments'.

16     capture(captureRequest: GenericRequest<IPayments.ModificationRequest>, requestOptions?: IRequest.Options): Promise<IPayments.ModificationResult>;
                                                                                                                          ~~~~~~~~~

node_modules/@adyen/api-library/dist/lib/src/services/modification.d.ts:17:58 - error TS2503: Cannot find namespace 'IPayments'.

17     cancelOrRefund(cancelOrRefundRequest: GenericRequest<IPayments.ModificationRequest>, requestOptions?: IRequest.Options): Promise<IPayments.ModificationResult>;
                                                            ~~~~~~~~~

node_modules/@adyen/api-library/dist/lib/src/services/modification.d.ts:17:107 - error TS2503: Cannot find namespace 'IRequest'.

17     cancelOrRefund(cancelOrRefundRequest: GenericRequest<IPayments.ModificationRequest>, requestOptions?: IRequest.Options): Promise<IPayments.ModificationResult>;
                                                                                                             ~~~~~~~~

node_modules/@adyen/api-library/dist/lib/src/services/modification.d.ts:17:134 - error TS2503: Cannot find namespace 'IPayments'.

17     cancelOrRefund(cancelOrRefundRequest: GenericRequest<IPayments.ModificationRequest>, requestOptions?: IRequest.Options): Promise<IPayments.ModificationResult>;
                                                                                                                                        ~~~~~~~~~

node_modules/@adyen/api-library/dist/lib/src/services/modification.d.ts:18:42 - error TS2503: Cannot find namespace 'IPayments'.

18     refund(refundRequest: GenericRequest<IPayments.ModificationRequest>, requestOptions?: IRequest.Options): Promise<IPayments.ModificationResult>;
                                            ~~~~~~~~~

node_modules/@adyen/api-library/dist/lib/src/services/modification.d.ts:18:91 - error TS2503: Cannot find namespace 'IRequest'.

18     refund(refundRequest: GenericRequest<IPayments.ModificationRequest>, requestOptions?: IRequest.Options): Promise<IPayments.ModificationResult>;
                                                                                             ~~~~~~~~

node_modules/@adyen/api-library/dist/lib/src/services/modification.d.ts:18:118 - error TS2503: Cannot find namespace 'IPayments'.

18     refund(refundRequest: GenericRequest<IPayments.ModificationRequest>, requestOptions?: IRequest.Options): Promise<IPayments.ModificationResult>;
                                                                                                                        ~~~~~~~~~

node_modules/@adyen/api-library/dist/lib/src/services/modification.d.ts:19:42 - error TS2503: Cannot find namespace 'IPayments'.

19     cancel(cancelRequest: GenericRequest<IPayments.ModificationRequest>, requestOptions?: IRequest.Options): Promise<IPayments.ModificationResult>;
                                            ~~~~~~~~~

node_modules/@adyen/api-library/dist/lib/src/services/modification.d.ts:19:91 - error TS2503: Cannot find namespace 'IRequest'.

19     cancel(cancelRequest: GenericRequest<IPayments.ModificationRequest>, requestOptions?: IRequest.Options): Promise<IPayments.ModificationResult>;
                                                                                             ~~~~~~~~

node_modules/@adyen/api-library/dist/lib/src/services/modification.d.ts:19:118 - error TS2503: Cannot find namespace 'IPayments'.

19     cancel(cancelRequest: GenericRequest<IPayments.ModificationRequest>, requestOptions?: IRequest.Options): Promise<IPayments.ModificationResult>;
                                                                                                                        ~~~~~~~~~

node_modules/@adyen/api-library/dist/lib/src/services/modification.d.ts:20:60 - error TS2503: Cannot find namespace 'IPayments'.

20     technicalCancel(technicalCancelRequest: GenericRequest<IPayments.ModificationRequest>, requestOptions?: IRequest.Options): Promise<IPayments.ModificationResult>;
                                                              ~~~~~~~~~

node_modules/@adyen/api-library/dist/lib/src/services/modification.d.ts:20:109 - error TS2503: Cannot find namespace 'IRequest'.

20     technicalCancel(technicalCancelRequest: GenericRequest<IPayments.ModificationRequest>, requestOptions?: IRequest.Options): Promise<IPayments.ModificationResult>;
                                                                                                               ~~~~~~~~

node_modules/@adyen/api-library/dist/lib/src/services/modification.d.ts:20:136 - error TS2503: Cannot find namespace 'IPayments'.

20     technicalCancel(technicalCancelRequest: GenericRequest<IPayments.ModificationRequest>, requestOptions?: IRequest.Options): Promise<IPayments.ModificationResult>;
                                                                                                                                          ~~~~~~~~~

node_modules/@adyen/api-library/dist/lib/src/services/modification.d.ts:21:68 - error TS2503: Cannot find namespace 'IPayments'.

21     adjustAuthorisation(adjustAuthorisationRequest: GenericRequest<IPayments.ModificationRequest>, requestOptions?: IRequest.Options): Promise<IPayments.ModificationResult>;
                                                                      ~~~~~~~~~

node_modules/@adyen/api-library/dist/lib/src/services/modification.d.ts:21:117 - error TS2503: Cannot find namespace 'IRequest'.

21     adjustAuthorisation(adjustAuthorisationRequest: GenericRequest<IPayments.ModificationRequest>, requestOptions?: IRequest.Options): Promise<IPayments.ModificationResult>;
                                                                                                                       ~~~~~~~~

node_modules/@adyen/api-library/dist/lib/src/services/modification.d.ts:21:144 - error TS2503: Cannot find namespace 'IPayments'.

21     adjustAuthorisation(adjustAuthorisationRequest: GenericRequest<IPayments.ModificationRequest>, requestOptions?: IRequest.Options): Promise<IPayments.ModificationResult>;
                                                                                                                                                  ~~~~~~~~~

node_modules/@adyen/api-library/dist/lib/src/services/payout.d.ts:11:45 - error TS2503: Cannot find namespace 'IPayouts'.

11     storeDetailAndSubmitThirdParty(request: IPayouts.StoreDetailAndSubmitRequest): Promise<IPayouts.StoreDetailAndSubmitResponse>;
                                               ~~~~~~~~

node_modules/@adyen/api-library/dist/lib/src/services/payout.d.ts:11:92 - error TS2503: Cannot find namespace 'IPayouts'.

11     storeDetailAndSubmitThirdParty(request: IPayouts.StoreDetailAndSubmitRequest): Promise<IPayouts.StoreDetailAndSubmitResponse>;
                                                                                              ~~~~~~~~

node_modules/@adyen/api-library/dist/lib/src/services/payout.d.ts:12:32 - error TS2503: Cannot find namespace 'IPayouts'.

12     confirmThirdParty(request: IPayouts.ModifyRequest): Promise<IPayouts.ModifyResponse>;
                                  ~~~~~~~~

node_modules/@adyen/api-library/dist/lib/src/services/payout.d.ts:12:65 - error TS2503: Cannot find namespace 'IPayouts'.

12     confirmThirdParty(request: IPayouts.ModifyRequest): Promise<IPayouts.ModifyResponse>;
                                                                   ~~~~~~~~

node_modules/@adyen/api-library/dist/lib/src/services/payout.d.ts:13:32 - error TS2503: Cannot find namespace 'IPayouts'.

13     declineThirdParty(request: IPayouts.ModifyRequest): Promise<IPayouts.ModifyResponse>;
                                  ~~~~~~~~

node_modules/@adyen/api-library/dist/lib/src/services/payout.d.ts:13:65 - error TS2503: Cannot find namespace 'IPayouts'.

13     declineThirdParty(request: IPayouts.ModifyRequest): Promise<IPayouts.ModifyResponse>;
                                                                   ~~~~~~~~

node_modules/@adyen/api-library/dist/lib/src/services/payout.d.ts:14:26 - error TS2503: Cannot find namespace 'IPayouts'.

14     storeDetail(request: IPayouts.StoreDetailRequest): Promise<IPayouts.StoreDetailResponse>;
                            ~~~~~~~~

node_modules/@adyen/api-library/dist/lib/src/services/payout.d.ts:14:64 - error TS2503: Cannot find namespace 'IPayouts'.

14     storeDetail(request: IPayouts.StoreDetailRequest): Promise<IPayouts.StoreDetailResponse>;
                                                                  ~~~~~~~~

node_modules/@adyen/api-library/dist/lib/src/services/payout.d.ts:15:31 - error TS2503: Cannot find namespace 'IPayouts'.

15     submitThirdparty(request: IPayouts.SubmitRequest): Promise<IPayouts.SubmitResponse>;
                                 ~~~~~~~~

node_modules/@adyen/api-library/dist/lib/src/services/payout.d.ts:15:64 - error TS2503: Cannot find namespace 'IPayouts'.

15     submitThirdparty(request: IPayouts.SubmitRequest): Promise<IPayouts.SubmitResponse>;
                                                                  ~~~~~~~~

node_modules/@adyen/api-library/dist/lib/src/services/payout.d.ts:16:21 - error TS2503: Cannot find namespace 'IPayouts'.

16     payout(request: IPayouts.PayoutRequest): Promise<IPayouts.PayoutResponse>;
                       ~~~~~~~~

node_modules/@adyen/api-library/dist/lib/src/services/payout.d.ts:16:54 - error TS2503: Cannot find namespace 'IPayouts'.

16     payout(request: IPayouts.PayoutRequest): Promise<IPayouts.PayoutResponse>;
                                                        ~~~~~~~~

node_modules/@adyen/api-library/dist/lib/src/services/recurring.d.ts:7:35 - error TS2503: Cannot find namespace 'IRecurring'.

7     listRecurringDetails(request: IRecurring.RecurringDetailsRequest): Promise<IRecurring.RecurringDetailsResult>;
                                    ~~~~~~~~~~

node_modules/@adyen/api-library/dist/lib/src/services/recurring.d.ts:7:80 - error TS2503: Cannot find namespace 'IRecurring'.

7     listRecurringDetails(request: IRecurring.RecurringDetailsRequest): Promise<IRecurring.RecurringDetailsResult>;
                                                                                 ~~~~~~~~~~

node_modules/@adyen/api-library/dist/lib/src/services/recurring.d.ts:8:22 - error TS2503: Cannot find namespace 'IRecurring'.

8     disable(request: IRecurring.DisableRequest): Promise<IRecurring.DisableResult>;
                       ~~~~~~~~~~

node_modules/@adyen/api-library/dist/lib/src/services/recurring.d.ts:8:58 - error TS2503: Cannot find namespace 'IRecurring'.

8     disable(request: IRecurring.DisableRequest): Promise<IRecurring.DisableResult>;
                                                           ~~~~~~~~~~

server/payment/payment.service.ts:5:39 - error TS2306: File '/Users/alexandru.aldulea/workspace/frontend-post-login/node_modules/@adyen/api-library/dist/lib/src/typings/checkout.d.ts' is not a module.

5 import { PaymentMethodsRequest } from '@adyen/api-library/dist/lib/src/typings/checkout'
                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version: v12.13.0
 - NPM Version: 6.12.0

**Additional context**
tsconfig:
```{
  "compilerOptions": {
    "module": "commonjs",
    "declaration": true,
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es2017",
    "sourceMap": true,
    "outDir": "./dist",
    "baseUrl": "./",
    "incremental": true,
    "esModuleInterop": true,
    "lib": [
      "es2019",
      "esnext.array"
    ]
  },
  "exclude": ["node_modules", "dist", "src"]
}
```

**Comment by KadoBOT** [comment]
Hi @aldulea thanks for opening this issue.

While I work on a fix, does `v2.1.8` suits your needs? I might add the type definitions to @types, but I'm not sure how long it can take.

Thanks,

**Comment by aldulea** [comment]
Hi @KadoBOT. Yes, `v2.1.8` is fine for now. 

Thanks

**Comment by KadoBOT** [comment]
Hi @aldulea, this should be fixed with release v2.2.1. Let me know if you find any issue.

Thanks,
