### ISSUE TITLE
[BUG] TypeError: data.toISOString is not a function

### ISSUE THREAD

**Issue by endze1t** [Adyen/adyen-node-api-library#1230]
After upgrading to v14.0.0 (from v13.x) we are receiving a type error on Date (string) properties on `CheckoutAPI.PaymentsApi.payments({...})`

Example:
https://docs.adyen.com/api-explorer/Checkout/70/post/payments#request-accountInfo-accountCreationDate

`accountCreationDate` should be a string (example: "1990-01-01"). We are sending this string but it seems like the new v14 expecting a Datetime Object now that supports `toISOString()` function.

Typescript says now this must be a Date Object. Is this intended?

Other properties like `dateOfBirth` just still a String, not a Date object.

full error:
```
TypeError: data.toISOString is not a function
    at ObjectSerializer.serialize (C:\codebase\node_modules\@adyen\api-library\lib\src\typings\checkout\models.js:807:25)
    at ObjectSerializer.serialize (C:\codebase\node_modules\@adyen\api-library\lib\src\typings\checkout\models.js:827:69)
    at PaymentsApi.payments (C:\codebase\node_modules\@adyen\api-library\lib\src\services\checkout\paymentsApi.js:91:51)
    at C:\codebase\test\testing.js:158:55
    at Object.<anonymous> (C:\codebase\test\testing.js:166:3)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47
```
